CONTIKI_PROJECT = testapp3

NRF52_SDK_ROOT=/home/johan/Downloads/nrf5_iot_sdk_3288530

CONTIKI_WITH_RPL=0
NRF52_WITHOUT_SOFTDEVICE=0

all: $(CONTIKI_PROJECT) 

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
