shell_src = shell.c shell-reboot.c shell-vars.c shell-ps.c \
            shell-blink.c shell-text.c shell-time.c \
            shell-file.c shell-run.c \
            shell-coffee.c \
            shell-power.c \
            shell-base64.c \
            shell-memdebug.c \
	    shell-powertrace.c shell-crc.c

ifeq ($(CONTIKI_WITH_RIME),1)
shell_src += shell-rime.c shell-sendtest.c \
            shell-rime-ping.c shell-rime-sniff.c shell-rime-netcmd.c \
            shell-rime-debug.c shell-rime-debug-runicast.c \
            shell-rime-sendcmd.c shell-download.c shell-rime-neighbors.c \
			shell-rime-unicast.c shell-netperf.c \
			shell-collect-view.c 

APPS += collect-view
include $(CONTIKI)/apps/collect-view/Makefile.collect-view
endif

ifeq ($(CONTIKI_WITH_IPV4),1)
	SHELL_WITH_IP = 1
endif
ifeq ($(CONTIKI_WITH_IPV6),1)
	SHELL_WITH_IP = 1
endif

ifeq ($(SHELL_WITH_IP),1)
shell_src += shell-netstat.c

endif

APPS += powertrace
include $(CONTIKI)/apps/powertrace/Makefile.powertrace

ifeq ($(TARGET),sky)
  shell_src += shell-sky.c
endif

ifeq ($(TARGET),z1)
  shell_src += shell-sky.c
endif
