EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/exp5438 \
hello-world/native \
hello-world/sky \
hello-world/wismote \
hello-world/z1 \
hello-world/cc2538dk \
er-rest-example/sky \
er-rest-example/cc2538dk \
powertrace/sky \
powertrace/cc2538dk \
rime/sky \
rime/z1 \
sky/sky \
z1/z1 \
tcp-socket/sky \
tcp-socket/cc2538dk \
ipv6/multicast/sky \
ipv6/multicast/cc2538dk \
ipv6/rpl-udp/sky \
ipv6/rpl-udp/cc2538dk \
ipv6/rpl-collect/cc2538dk \
ipv6/rpl-border-router/cc2538dk \


TOOLS=

include ../Makefile.compile-test
