CONTIKI_PROJECT = contikible

NRF52_SDK_ROOT=/home/johan/Downloads/nRF52_SDK_0.9.2_dbc28c9

CONTIKI_WITH_RPL=1
NRF52_WITHOUT_SOFTDEVICE=0

all: $(CONTIKI_PROJECT) 

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
